// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "semver_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// parse_ptr
List parse_ptr(std::vector< std::string > versions);
RcppExport SEXP semver_parse_ptr(SEXP versionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector< std::string > >::type versions(versionsSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_ptr(versions));
    return rcpp_result_gen;
END_RCPP
}
// render_ptr
Rcpp::StringVector render_ptr(semver200 verPtr);
RcppExport SEXP semver_render_ptr(SEXP verPtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< semver200 >::type verPtr(verPtrSEXP);
    rcpp_result_gen = Rcpp::wrap(render_ptr(verPtr));
    return rcpp_result_gen;
END_RCPP
}
// ptr_comparator
int ptr_comparator(semver200 verPtr1, semver200 verPtr2);
RcppExport SEXP semver_ptr_comparator(SEXP verPtr1SEXP, SEXP verPtr2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< semver200 >::type verPtr1(verPtr1SEXP);
    Rcpp::traits::input_parameter< semver200 >::type verPtr2(verPtr2SEXP);
    rcpp_result_gen = Rcpp::wrap(ptr_comparator(verPtr1, verPtr2));
    return rcpp_result_gen;
END_RCPP
}
