# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_ptr <- function(versions) {
    .Call('semver_parse_ptr', PACKAGE = 'semver', versions)
}

render_ptr <- function(verPtr) {
    .Call('semver_render_ptr', PACKAGE = 'semver', verPtr)
}

ptr_comparator <- function(verPtr1, verPtr2) {
    .Call('semver_ptr_comparator', PACKAGE = 'semver', verPtr1, verPtr2)
}

